#!/usr/bin/env python
import os
import sys
import json
import argparse

from redis import StrictRedis

redis = StrictRedis()

def client(user, filename, listen_key):
    filename = os.path.abspath(filename)
    if os.path.isfile(filename):
        print "Sending File"
        msg = {
            'filename': filename,
            'user': user
        }
        redis.lpush(listen_key, json.dumps(msg))

    elif os.path.isdir(filename):
        print "Sending Directory"
        for root,directories, filenames in os.walk(filename):
            for file in filenames:
                msg = {
                    'filename': os.path.join(root,file),
                    'user': user
                }
                redis.lpush(listen_key, json.dumps(msg))
    else:
        print "No such file or directory"

def status(listen_key):
    items = redis.lrange(listen_key, 0, -1)
    if len(items) == 0:
        print "No pending jobs"
    else:
        for number, job in enumerate(items, start=1):
            print "{}) {}".format(number, job)


parser = argparse.ArgumentParser(description="cli for sending jobs to the report parser from the command line")
subparsers = parser.add_subparsers(help="sub-command help", dest="command")

create_parser = subparsers.add_parser('create', help="Create a job")
create_parser.add_argument('user', help="the username or id to store with the report")
create_parser.add_argument('filename', help="the file or directory to send to the report daemon")

status_parser = subparsers.add_parser('status', help="View the status the job queue")

args = parser.parse_args()

if args.command == "status":
    status('report-listen-queue')
else:

    client(args.user, args.filename, 'report-listen-queue')
